export const AGREGAR_PRODUCTO_TYPE = "AGREGAR_PRODUCTO";
export const ELIMINAR_PRODUCTO_TYPE = "ELIMINAR_PRODUCTO";
export const VACIAR_CARRITO_TYPE = "VACIAR_CARRITO";
export const INCREMENTAR_ITEM_TYPE = "INCREMENTAR_ITEM";
export const DECREMENTAR_ITEM_TYPE = "DECREMENTAR_ITEM";