export const AGREGAR_PRODUCTO_CATALOGO_TYPE = "AGREGAR_PRODUCTO_CATALOGO";
export const EDITAR_PRODUCTO_CATALOGO_TYPE = "EDITAR_PRODUCTO_CATALOGO";
export const ELIMINAR_PRODUCTO_CATALOGO_TYPE = "ELIMINAR_PRODUCTO_CATALOGO";